// spotify-with-next/src/components/ArtistCard.tsx
import Image from 'next/image';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlay } from '@fortawesome/free-solid-svg-icons';
import { Artist } from '@/models/artist';

interface ArtistCardProps {
  artist: Artist;
}

export function ArtistCard({ artist }: ArtistCardProps) {
  return (
    <div className="p-4 w-full relative flex-1 bg-card_bg rounded-lg hover:bg-card_hover_bg transition-colors duration-75 group">
      <div className="w-full relative">
        <Image
          className="rounded-full"
          src={artist.urlImg}
          alt=""
          width={300}
          height={300}
        />
        <div className="relative">
          <div className="absolute -top-12 right-2 w-12 h-12 flex items-center justify-center bg-play_bg text-sm rounded-full opacity-0 group-hover:opacity-100 group-hover:-translate-y-3 gr transition-all duration-300">
            <FontAwesomeIcon icon={faPlay} />
          </div>
        </div>
      </div>

      <Link href="#">
        <div className="pt-4 flex flex-col gap-1">
          <span className="font-bold text-primary_text">{artist.name}</span>
          <span className="text-secondary_text">{artist.genre}</span>
        </div>
      </Link>
    </div>
  );
}

// spotify-with-angular/src/app/components/artist-card/artist-card.component.ts
import { Component, Input } from '@angular/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faPlay } from '@fortawesome/free-solid-svg-icons';
import { Artist } from '../../../models/artist';

@Component({
  selector: 'app-artist-card',
  imports: [FontAwesomeModule],
  templateUrl: './artist-card.component.html',
})
export class ArtistCardComponent {
  faPlay = faPlay;
  @Input('artist') artist!: Artist;
}

<div
  class="p-4 w-full relative flex-1 bg-card_bg rounded-lg hover:bg-card_hover_bg transition-colors duration-75 group"
>
  <div class="w-full relative">
    <img
      class="rounded-full"
      src="{{ artist.urlImg }}"
      alt=""
      class="w-[300px] h-auto"
    />
    <div class="relative">
      <div
        class="absolute -top-12 right-2 w-12 h-12 flex items-center justify-center bg-play_bg text-sm rounded-full opacity-0 group-hover:opacity-100 group-hover:-translate-y-3 gr transition-all duration-300"
      >
        <fa-icon [icon]="faPlay"></fa-icon>
      </div>
    </div>
  </div>

  <a href="#">
    <div class="pt-4 flex flex-col gap-1">
      <span class="font-bold text-primary_text">{{ artist.name }}</span>
      <span class="text-secondary_text">{{ artist.genre }}</span>
    </div>
  </a>
</div>
