// spotify-with-angular/src/app/pages/search/search.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-search',
  imports: [],
  templateUrl: './search.component.html',
})
export class SearchComponent {}

<div
  class="w-full h-full px-6 py-[60px] flex flex-col gap-4 bg-secondary_bg rounded-lg overflow-y-scroll"
>
  <h2 class="font-bold text-2xl">Navegar por todas as seções</h2>

  <div
    class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-4 justify-center"
  >
    <div *ngFor="let offer of offers" class="w-full">
      <app-offer-card
        [title]="offer.title"
        [imageUrl]="offer.imageUrl"
        [color]="offer.color"
      ></app-offer-card>
    </div>
  </div>
</div>

// spotify-with-next/src/app/new/search/page.tsx
import { OfferList } from '@/components/OfferList';

export default function SearchPageMain() {
  return (
    <div className="w-full h-full px-6 py-[60px] flex flex-col bg-secondary_bg rounded-lg overflow-y-scroll">
      <h2 className="font-bold text-2xl">Navegar por todas as seções</h2>

      <OfferList />
    </div>
  );
}
