// spotify-with-next/src/components/OfferCard.tsx
import Image from 'next/image';
import Link from 'next/link';
import { HtmlHTMLAttributes } from 'react';

interface OfferCardProps extends HtmlHTMLAttributes<HTMLDivElement> {
  title: string;
  imageUrl: string;
}

export function OfferCard({ title, imageUrl, className }: OfferCardProps) {
  return (
    <Link href="#">
      <div
        className={`h-[162px] relative overflow-hidden rounded-lg ${className}`}
      >
        <Image
          src={imageUrl}
          alt=""
          width={120}
          height={120}
          className="absolute right-0 bottom-0 w-[120px] h-auto rotate-[25deg] translate-x-[18%] translate-y-[2%] rounded"
        />
        <span className="p-4 absolute text-primary_text text-2xl font-bold">
          {title}
        </span>
      </div>
    </Link>
  );
}

// spotify-with-angular/src/app/components/offer-card/offer-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-offer-card',
  imports: [],
  templateUrl: './offer-card.component.html',
})
export class OfferCardComponent {
  @Input('title') title: string = '';
  @Input('imageUrl') imageUrl: string = '';
}

<a href="#">
  <div class="h-[162px] relative overflow-hidden rounded-lg">
    <img
      src="{{ imageUrl }}"
      alt=""
      class="absolute right-0 bottom-0 w-[120px] h-auto rotate-[25deg] translate-x-[18%] translate-y-[2%] rounded"
    />
    <span class="p-4 absolute text-primary_text text-2xl font-bold">
      {{ title }}
    </span>
  </div>
</a>
